### ISSUE TITLE
step crashing on windows with AWS provisioner

### ISSUE THREAD

**Issue by jokreliable** [smallstep/cli#465]
### Subject of the issue
step crashes on windows with AWS provisioner. 

### Your environment
* OS - Windows server
* Version - 2019 (1809) ami-077475371a476c548

### Steps to reproduce
When i run: 
`\Step\step_0.15.16\bin\step.exe --config C:\step\step.json ca certificate --provisioner Amazon hostnamehere \ProgramData\puppetlabs\puppet\etc\ssl\certs\hostname.pem \ProgramData\puppetlabs\puppet\etc\ssl\private_keys\hostname.pem`
it crashes with the following output on windows:
```
✔ Provisioner: Amazon (AWS)
Something unexpected happened.
If you want to help us debug the problem, please run:
STEPDEBUG=1 \Step\step_0.15.16\bin\step.exe --config C:\step\step.json ca certificate --provisioner Amazon hostname \ProgramData\puppetlabs\puppet\etc\ssl\certs\hostname.pem \ProgramData\puppetlabs\puppet\etc\ssl\private_keys\hostname.pem
and send the output to info@smallstep.com
```
(note the output should be `$Env:STEPDEBUG=1; step.exe ...` -- the syntax above doesn't work on windows)

output with debug:
```
✔ Provisioner: Amazon (AWS)
Smallstep CLI/0.15.16 (windows/amd64)
Release Date: 2021-04-15T22:33:22Z

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xf3a3be]

goroutine 1 [running]:
main.panicHandler()
        command-line-arguments/main.go:121 +0x390
panic(0x14ce580, 0x1ea8ed0)
        runtime/panic.go:965 +0x1c7
github.com/smallstep/certificates/authority/provisioner.(*AWS).readURL(0xc000170c80, 0x1698967, 0x40, 0x0, 0x0, 0x1, 0x0, 0xc0000a46c0)
        github.com/smallstep/certificates@v0.15.14/authority/provisioner/aws.go:534 +0x15e
github.com/smallstep/certificates/authority/provisioner.(*AWS).GetIdentityToken(0xc000170c80, 0xc000032200, 0x1a, 0xc00002c7b0, 0x21, 0xc000170c80, 0x0, 0x0, 0x0)
        github.com/smallstep/certificates@v0.15.14/authority/provisioner/aws.go:318 +0xaf
github.com/smallstep/cli/utils/cautils.NewTokenFlow(0xc0000c8b00, 0x0, 0xc000032200, 0x1a, 0x1f1e588, 0x0, 0x0, 0xc00002c7b0, 0x21, 0xc000030618, ...)
        github.com/smallstep/cli/utils/cautils/token_flow.go:131 +0x5e5
github.com/smallstep/cli/utils/cautils.(*CertificateFlow).GenerateToken(0xc0000552c0, 0xc0000c8b00, 0xc000032200, 0x1a, 0x1f1e588, 0x0, 0x0, 0x1822910, 0x1471ee0, 0x0, ...)
        github.com/smallstep/cli/utils/cautils/certificate_flow.go:137 +0x1a5
github.com/smallstep/cli/command/ca.certificateAction(0xc0000c8b00, 0x0, 0x0)
        github.com/smallstep/cli/command/ca/certificate.go:202 +0xbb2
github.com/smallstep/cli/command.ActionFunc.func1(0xc0000c8b00, 0x0, 0x0)
        github.com/smallstep/cli/command/command.go:48 +0x46
github.com/urfave/cli.HandleAction(0x14b80a0, 0xc00020ed10, 0xc0000c8b00, 0xc0000c8b00, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:524 +0xc2
```

### Expected behaviour
A certificate is generated. (at it stands, only the key is generated).

### Actual behaviour
Key is generated, but not the cert. Software crashes. 

### Additional context
It appears that connection to various AWS meta-data endpoints (both v1 and v2) are working (user mariono cano on gitter helped me get some additional info here)

```
$StepZipTemp = "\windows\TEMP\step.zip"
$StepInstallPath = "\Step"
$StepZipURL = "https://github.com/smallstep/cli/releases/download/v0.15.16/step_windows_0.15.16_amd64.zip"

if (! (Test-Path $StepInstallPath) ) {
    New-Item -ItemType Directory -Name $StepInstallPath -path "C:\"
} 

# download and extract
Write-Output "Step - Install"
Invoke-WebRequest -Uri $StepZipURL -OutFile $StepZipTemp
Expand-Archive -LiteralPath $StepZipTemp -DestinationPath "C:\Step"

Write-Output "Step - Config"
# some basic config for step
$stepJson = @'
{
    "ca-url": "https://step-ca-root-here",
    "fingerprint": "12345678....",
    "root": "C:\\Step\\root_ca.crt",
    "redirect-url": ""
}
'@
Set-Content "$StepInstallPath\step.json" -value $stepJson

$StepRootCA = @'
-----BEGIN CERTIFICATE-----
blahblah
-----END CERTIFICATE-----
'@
Set-Content "C:\step\root_ca.crt" -Value $StepRootCA

# generate/get certs
& "\Step\step_0.15.16\bin\step.exe" `
    --config "C:\step\step.json" `
    ca certificate --provisioner Amazon `
    hostname `
    \ProgramData\puppetlabs\puppet\etc\ssl\certs\hostname.pem `
    \ProgramData\puppetlabs\puppet\etc\ssl\private_keys\hostname.pem
```
(a number of parameters need to be tweaked, and directories created for this to work as-is -- but this is the core bits used to run step at this time -- I hope this helps reproduce the problem.)

**Comment by dopey** [comment]
Thanks @jokreliable for the detailed bug report. We've added to our bug backlog. We think the fix should be easy, but the most challenging part for us will be reproducing with a Windows server running on AWS. As a team we don't have a whole lot of experience with Windows. 

If anyone from the community has a Windows server running in AWS and time to do a bit of debugging, we would wholeheartedly appreciate a PR :)

**Comment by jokreliable** [comment]
so i've been trying for the last couple hours to get a debug version of step built and finally succeeded. 

It looks like the code is panic'ing when it reaches this code:
https://github.com/smallstep/certificates/blob/f83ccc31d18d782f142fdd74f8c0f6ad39c672c6/authority/provisioner/aws.go#L508

It seems like p.IMDSVersions is nil. (I would have expected it to be defined in the init function in that same file though, L383).
I expect that since it's nil, the for loop skips, bypassing the whole thing off to L530, where nil is still uninitialized, and then the return at L533 resp is still nil, so trying to return the statuscode crashes the client.

**Comment by jokreliable** [comment]
a horrible thing: 
```
func (p *AWS) readURL(url string) ([]byte, error) {
	var resp *http.Response
	var err error
	IMDSVer := [2]string{"v2", "v1"}

	for _, v := range IMDSVer {
		switch v {
		case "v1":
```

Seems to make it make it possible to get the certificate generated. Obviously, this is not a real fix, but it confirms that the problem is not in CLI, but in the provisioner inside "smallstep/certificate". (though i'm still curious why none of the breakpoints on `Init` triggered... 

I hope those are enough breadcrumbs to get you to the fix for this.
