### ISSUE TITLE
[Bug]: `step oauth --help` crashes

### ISSUE THREAD

**Issue by tashian** [smallstep/cli#706]
### Steps to Reproduce

1. Run `step oauth --help`

### Your Environment

* OS - tested on Ubuntu and Darwin
* `step` CLI Version - 0.21.0 and `master` (0.21.0-29-g3586b16)
* tested with an empty `~/.step`

### Expected Behavior

I expected help to appear

### Actual Behavior

```
$ STEPDEBUG=1 step oauth --help
Smallstep CLI/0.21.0 (linux/amd64)
Release Date: 2022-07-06T22:23:54Z

panic: runtime error: index out of range [-1] [recovered]
	panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.panicHandler()
	./main.go:139 +0x245
panic({0x12dec00, 0xc00046cfa8})
	runtime/panic.go:838 +0x207
github.com/smallstep/cli/usage.(*Renderer).RenderNode(0xc000598600, {0x15d2aa0?, 0xc000598690?}, 0xc0001e3b80, 0x1?)
	github.com/smallstep/cli/usage/renderer.go:302 +0x1875
github.com/smallstep/cli/pkg/blackfriday.Run.func1(0xc000855078?, 0xa7?)
	github.com/smallstep/cli/pkg/blackfriday/markdown.go:392 +0x39
github.com/smallstep/cli/pkg/blackfriday.(*Node).Walk(0xc000248900?, 0xc000855160)
	github.com/smallstep/cli/pkg/blackfriday/node.go:284 +0x57
github.com/smallstep/cli/pkg/blackfriday.Run({0xc0004f8000, 0x1b59, 0x2000}, {0xc0008551b8, 0x1, 0xc0004f4d9b?})
	github.com/smallstep/cli/pkg/blackfriday/markdown.go:391 +0x2aa
github.com/smallstep/cli/usage.Render({0xc0004f8000, 0x1b59, 0x2000})
	github.com/smallstep/cli/usage/renderer.go:19 +0xc5
github.com/smallstep/cli/usage.HelpPrinter({0x15d71c0, 0xc0001a2008}, {0x14115a8?, 0xc00007a030?}, {0x135b640?, 0xc000537b80?})
	github.com/smallstep/cli/usage/printer.go:30 +0x3a
github.com/urfave/cli.ShowCommandHelp(0xc0002f5340, {0x13746a0, 0x5})
	github.com/urfave/cli@v1.22.5/help.go:203 +0x50a
github.com/urfave/cli.checkCommandHelp(0xc0002f5340, {0x13746a0, 0x5})
	github.com/urfave/cli@v1.22.5/help.go:308 +0x7e
github.com/urfave/cli.Command.Run({{0x13746a0, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x13decfe, 0x33}, {0x141ee11, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:137 +0x4f1
github.com/urfave/cli.(*App).Run(0xc0002f3180, {0xc00018e150, 0x3, 0x3})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.main()
	./main.go:113 +0x611
```

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
[This PR](https://github.com/smallstep/cli/pull/707) fixes the help text rendering
